name: Scheduler

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

permissions:
  pull-requests: write
  actions: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update sponsors.svg
        run: npx sponsors-svg
        env:
          SPONSORS_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
          SPONSORS_LOGIN: codecalm

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
